### ISSUE TITLE
[HotFix] 지역 검색 페이지 취소 아이콘 중복 출력

### ISSUE THREAD

**Issue by ohamin26** [ohamin26/hair-salon-booking-site-front#10]
어떤 버그인가요?
지역 검색 페이지에서 취소 아이콘이 중복 출력 되는 거 같습니다!

참고할만한 자료(선택)

![image](https://github.com/user-attachments/assets/33cadd33-02de-404d-9c02-dd029b14d6ac)

**Comment by chlangus** [comment]
넵 아이콘 수정했습니다
